## Numpy

### Vector

In [2]:
import numpy as np

1. Addition of Vectors

In [3]:
vec1 = np.array([1,8,7])
vec2 = np.array([7,0,6])
add = vec1 + vec2
add

array([ 8,  8, 13])

In [5]:
v1=[-1,-7,8]
v2=[-1,4,-3]
add = v1+v2
add

[-1, -7, 8, -1, 4, -3]

In [6]:
v1=np.array([-1,-7,8])
v2=np.array([-1,4,-3])
add = v1+v2
add

array([-2, -3,  5])

2. Subtraction of Vectors

In [7]:
v1=np.array([7,8,3])
v2=np.array([0,4,1])
sub = v1-v2
sub

array([7, 4, 2])

In [ ]:
# error
# v1=[7,8,3]
# v2=[0,4,1]
# sub = v1-v2
# sub

In [10]:
v1=np.array([-7,-8,3])
v2=np.array([0,-4,1])
sub = v1-v2
sub

array([-7, -4,  2])

3. Scalar Multiplication (Scalar Product)

In [12]:
vec = np.array([4,8,9,1])
scaler = 4
mal = scaler*vec
mal

array([16, 32, 36,  4])

In [11]:
vec = [4,8,9,1]
scaler = 4
mal = scaler*vec
mal

[4, 8, 9, 1, 4, 8, 9, 1, 4, 8, 9, 1, 4, 8, 9, 1]

4. Dot Product (Scalar Product)

In [16]:
v1 = [1,3,-9]
v2 = [9,0,-1]
dot = np.dot(v1, v2)
dot

18

In [18]:
v1 = np.array([1,3,-9])
v2 = np.array([9,0,-1])
dot = v1 * v2
dot

array([9, 0, 9])

In [26]:
v1 = np.array([1,3,-9])
v2 = np.array([9,0,-1])
dot = np.dot(v1 , v2)
dot

18

5. Cross Product (Vector Product)

In [28]:
v1 = np.array([1,3,-2])
v2 = np.array([3,0,-1])
dot = np.cross(v1 , v2)
dot

array([-3, -5, -9])

6. Magnitude (Length) of a Vector

In [33]:
v1 = np.array([1,3,-2])
mag = np.sqrt(sum(np.square(v1)))
mag

3.7416573867739413

In [35]:
v1 = np.array([1,3,-2])
mag = np.linalg.norm(v1)
mag

3.7416573867739413

7. Unit Vector

In [46]:
v=np.arange(3)
v_hat = v/np.linalg.norm(v)
v_hat

array([0.        , 0.4472136 , 0.89442719])

In [47]:
v=np.array([0,3,4])
v_hat = v/np.linalg.norm(v)
v_hat

array([0. , 0.6, 0.8])

8. Vector Projection

In [49]:
u = np.array([1,1,1])
v = np.array([2,2,2])
proj = (np.dot(v, u) / np.dot(u, u)) * u
proj

array([2., 2., 2.])

In [48]:
import numpy as np

# 1. Vector Addition
def vector_addition(v1, v2):
    return np.add(v1, v2)

# 2. Dot Product (Scalar Product)
def dot_product(v1, v2):
    return np.dot(v1, v2)

# 3. Cross Product
def cross_product(v1, v2):
    return np.cross(v1, v2)

# 4. Magnitude (Norm) of a Vector
def magnitude(v):
    return np.linalg.norm(v)

# 5. Scalar Multiplication
def scalar_multiply(scalar, v):
    return scalar * v

# 6. Normalization of a Vector
def normalize(v):
    return v / np.linalg.norm(v)

# 7. Vector Projection onto Another Vector
def projection(v, u):
    return (np.dot(v, u) / np.dot(u, u)) * u

# 8. Angle Between Two Vectors
def angle_between(v1, v2):
    cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    return np.arccos(np.clip(cos_angle, -1.0, 1.0))  # Clip to avoid numerical errors

# 9. Vector Reflection
def vector_reflection(v, normal):
    normal = normalize(normal)
    return v - 2 * np.dot(v, normal) * normal

# 10. Vector Sum (Multiple Vectors)
def vector_sum(*vectors):
    return np.sum(vectors, axis=0)

# 11. Vector Decomposition (Radial and Tangential Components)
def radial_tangential(v, normal):
    normal = normalize(normal)
    radial = np.dot(v, normal) * normal
    tangential = v - radial
    return radial, tangential

# 12. Scalar Triple Product (Volume of Parallelepiped)
def scalar_triple_product(v1, v2, v3):
    return np.dot(v1, np.cross(v2, v3))

# 13. Cross Product of Three Vectors
def vector_cross_product_of_three(v1, v2, v3):
    return np.cross(np.cross(v1, v2), v3)

# 14. Coordinate Transformation (Cartesian to Polar for 2D)
def cartesian_to_polar(v):
    r = np.linalg.norm(v)
    theta = np.arctan2(v[1], v[0])
    return r, theta

# 15. Coordinate Transformation (Cartesian to Spherical for 3D)
def cartesian_to_spherical(v):
    r = np.linalg.norm(v)
    theta = np.arccos(v[2] / r)
    phi = np.arctan2(v[1], v[0])
    return r, theta, phi

# 16. Rotation Matrix for 2D Vector
def rotation_matrix_2d(theta):
    return np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta), np.cos(theta)]])

# 17. Rotation of a 2D Vector Using a Rotation Matrix
def rotate_vector_2d(v, theta):
    rotation_matrix = rotation_matrix_2d(theta)
    return np.dot(rotation_matrix, v)

# 18. Rotation of a 3D Vector Using a Rotation Matrix (Around Z-Axis)
def rotate_vector_3d(v, theta):
    rotation_matrix = np.array([[np.cos(theta), -np.sin(theta), 0],
                                [np.sin(theta), np.cos(theta), 0],
                                [0, 0, 1]])
    return np.dot(rotation_matrix, v)

# 19. Vector Product (Tensor Product)
def tensor_product(v1, v2):
    return np.outer(v1, v2)

# 20. Moment of a Force (Cross Product)
def moment_of_force(position, force):
    return np.cross(position, force)

# 21. Curl of a Vector Field (For 3D)
def curl_of_vector_field(v):
    curl = np.array([
        np.gradient(v[2], axis=1) - np.gradient(v[1], axis=2),
        np.gradient(v[0], axis=2) - np.gradient(v[2], axis=0),
        np.gradient(v[1], axis=0) - np.gradient(v[0], axis=1)
    ])
    return curl

# 22. Divergence of a Vector Field
def divergence_of_vector_field(v):
    return np.gradient(v[0], axis=0) + np.gradient(v[1], axis=1) + np.gradient(v[2], axis=2)

# 23. Jacobian Matrix of a Vector Function
def jacobian_matrix(f, x, y):
    df_dx = (f(x + 1e-5, y) - f(x, y)) / 1e-5
    df_dy = (f(x, y + 1e-5) - f(x, y)) / 1e-5
    return np.array([[df_dx, df_dy]])

# 24. Hessian Matrix of a Scalar Function
def hessian(f, x, y):
    d2f_dx2 = (f(x + 1e-5, y) - 2*f(x, y) + f(x - 1e-5, y)) / 1e-10
    d2f_dy2 = (f(x, y + 1e-5) - 2*f(x, y) + f(x, y - 1e-5)) / 1e-10
    d2f_dxdy = (f(x + 1e-5, y + 1e-5) - f(x + 1e-5, y - 1e-5) - f(x - 1e-5, y + 1e-5) + f(x - 1e-5, y - 1e-5)) / (4 * 1e-10)
    return np.array([[d2f_dx2, d2f_dxdy], [d2f_dxdy, d2f_dy2]])

# 25. Green’s Theorem for 2D
def greens_theorem(F, C, region):
    # For demonstration purposes: C is the curve, F is the vector field
    return np.sum(np.gradient(F[0], axis=0) + np.gradient(F[1], axis=1)) * region

# Example Usage:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
normal = np.array([0, 0, 1])
scalar = 5

# 1. Vector addition
print("Vector Addition:", vector_addition(v1, v2))

# 2. Dot product
print("Dot Product:", dot_product(v1, v2))

# 3. Cross product
print("Cross Product:", cross_product(v1, v2))

# 4. Magnitude
print("Magnitude of v1:", magnitude(v1))

# 5. Scalar multiplication
print("Scalar Multiplication:", scalar_multiply(scalar, v1))

# 6. Normalization
print("Normalized v1:", normalize(v1))

# 7. Projection
print("Projection of v1 onto v2:", projection(v1, v2))

# 8. Angle between vectors
print("Angle between v1 and v2:", angle_between(v1, v2))

# 9. Vector reflection
print("Reflection of v1:", vector_reflection(v1, normal))

# 10. Vector sum
print("Sum of v1, v2, v3:", vector_sum(v1, v2, v3))

# 11. Radial and tangential components
radial, tangential = radial_tangential(v1, normal)
print("Radial Component:", radial)
print("Tangential Component:", tangential)

# 12. Scalar triple product
print("Scalar Triple Product:", scalar_triple_product(v1, v2, v3))

# 13. Rotation matrix and vector rotation
theta = np.pi / 4  # 45 degrees
rotated_vector = rotate_vector_2d(v1[:2], theta)
print("Rotated 2D vector:", rotated_vector)


Vector Addition: [5 7 9]
Dot Product: 32
Cross Product: [-3  6 -3]
Magnitude of v1: 3.7416573867739413
Scalar Multiplication: [ 5 10 15]
Normalized v1: [0.26726124 0.53452248 0.80178373]
Projection of v1 onto v2: [1.66233766 2.07792208 2.49350649]
Angle between v1 and v2: 0.2257261285527342
Reflection of v1: [ 1.  2. -3.]
Sum of v1, v2, v3: [12 15 18]
Radial Component: [0. 0. 3.]
Tangential Component: [1. 2. 0.]
Scalar Triple Product: 0
Rotated 2D vector: [-0.70710678  2.12132034]
